### ISSUE TITLE
OFDM_SYS.v is missing

### ISSUE THREAD

**Issue by jinsanko** [phthinh/OFDM_802_16#3]
Please check whether we need a /script  folder and a tcl file  to run the OFDM_SYS_802_16 project.

Thanks.

Jinsan Ko

**Comment by phthinh** [comment]
Hi Jinsan Ko,
Thanks for raising the issue! For the OFDM_SYS_802_16 project, the top module is OFDM_SYS.sch instead of OFDM_SYS.v. Unlike the OFDM_/[TX/RX] projects, this project, unfortunately, did not come with a Tcl script to automatically regenerate the system in a Vivado project.  
Cheers,
Thinh

**Comment by jinsanko** [comment]
Thanks.

**Comment by jinsanko** [comment]
Thanks.
#3 is closed.
